# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Build
          command: |
            npm run lint
      - run:
          name: Throw Error
          command: |
            echo "Your job has been failed!"
          when: on_fail
            
  test:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Test
          command: |
           npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Audit
          command: |
           npm run audit


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test